AWSTemplateFormatVersion: "2010-09-09"

Description: TodobackenTodobackend Application

Resources:
  ApplicationCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: todobackend-cluster